spring.application.name=Internship


spring.datasource.url=jdbc:postgresql://postgres:5432/Notes
spring.datasource.username=postgres
spring.datasource.password=helloworld!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=redis
spring.data.redis.port=6379


# Actuator - expose all endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Swagger UI config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# App info (shows in /actuator/info)
info.app.name=Notes App
info.app.version=1.0.0
